#!/bin/bash
# Fixed Railway Database Backup Script

echo "=== Railway Database Backup Script (Fixed) ==="
echo ""
echo "Please follow these steps to backup your Railway database:"
echo ""
echo "1. Login to Railway:"
echo "   railway login"
echo ""
echo "2. Connect to your database service:"
echo "   railway ssh --project=4c060edd-949a-4d83-95ca-892b64b1356d --environment=8b189df9-aa8f-4f05-a5a4-85e443d66d36 --service=7955626a-881b-4138-9a56-97c544f07ee7"
echo ""
echo "3. Once connected, first check the environment variables:"
echo "   echo \"PGUSER: \$PGUSER\""
echo "   echo \"PGHOST: \$PGHOST\""  
echo "   echo \"PGPORT: \$PGPORT\""
echo "   echo \"PGDATABASE: \$PGDATABASE\""
echo ""
echo "4. Then run the backup command (try one of these options):"
echo ""
echo "   Option A (if environment variables are set):"
echo "   pg_dump --clean --no-owner --no-privileges > /tmp/metabase_backup.sql"
echo ""
echo "   Option B (if you need to specify manually):"
echo "   pg_dump -U [username] -h [host] -p [port] -d [database] --clean --no-owner --no-privileges > /tmp/metabase_backup.sql"
echo ""
echo "   Option C (try default postgres connection):"
echo "   pg_dump -h localhost --clean --no-owner --no-privileges > /tmp/metabase_backup.sql"
echo ""
echo "5. Exit the SSH connection:"
echo "   exit"
echo ""
echo "6. Copy the backup file to your local machine:"
echo "   railway ssh --project=4c060edd-949a-4d83-95ca-892b64b1356d --environment=8b189df9-aa8f-4f05-a5a4-85e443d66d36 --service=7955626a-881b-4138-9a56-97c544f07ee7 -- cat /tmp/metabase_backup.sql > ./metabase_backup.sql"
echo ""
echo "Note: If you see errors about roles or connections, try checking what databases exist:"
echo "   \\l      (list databases)"
echo "   \\du     (list users/roles)"
echo ""
echo "Once you have the backup file, run: ./import-database.sh"
echo ""

